backend:
  name: github
  repo: CBR0MS/qualis-red

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Post
    folder: posts
    create: true
    fields:
      - { name: path, label: Path, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list, default: [] }
      - {
          name: image,
          label: Image,
          widget: image,
          default: "images/default.jpg",
        }
      - { name: body, label: Body, widget: markdown }
